services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3000:3000'
    tty: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    volumes:
        - ./backend/:/var/www/
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_STORAGE=/var/www/storage
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - frontend
      - backend
  db:
    image: mysql:8.0.36
    container_name: db
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:  
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.conf 
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin
    environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    ports:
    - 8080:80