services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
        - ./:/var/www/
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_STORAGE=/var/www/storage
    depends_on:
      - db
  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    container_name: nginx-backend
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  db:
    image: mysql:8.0.36
    container_name: db-backend
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:  
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.conf 
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: test_phpmyadmin-backend
    image: phpmyadmin
    environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    ports:
    - 8080:80