services:
  frontend:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    tty: true
  nginx-frontend:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    container_name: nginx-frontend
    ports:
      - 81:81
    depends_on:
      - frontend